TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

QMAKE_CXXFLAGS += -O3 -ffast-math

SOURCES += \
    GUI/gui_control.cpp \
    GUI/gui_display.cpp \
    GUI/gui_fields_common.cpp \
    GUI/gui_fields_iso.cpp \
    GUI/gui_geom.cpp \
    GUI/gui_init.cpp \
    GUI/gui_text.cpp \
    GUI/gui_textures.cpp \
    GUI/gui_cameras.cpp \
    IO/IO_bmp.cpp \
    IO/IO_ppm.cpp \
    IO/IO_tecplot.cpp \
    IO/IO_tga.cpp \
    IO/IO_vtk.cpp \
    image/image_opencv.cpp \
    Main.cpp \
    GUI/gui_tracers.cpp \
    PMC/BinaryTreshold.cpp \
    PMC/DomainDetection.cpp \
    PMC/ParticleMaskCorrelation.cpp \
    PMC/PlanarContainer.cpp \
    MarkerIdentification/CalibrationTarget.cpp \
    MarkerIdentification/Marker.cpp \
    MarkerIdentification/MarkerSearcher.cpp \
    MarkerIdentification/MarkerSearcher_old.cpp \
    MarkerIdentification/MisalignmentCorr.cpp



unix{
LIBS+=  -lGL -lGLU -lglut -lm
}
win32{
LIBS += -lopenGL32 -lGLU32 -lm
LIBS += -L$$PWD/my_lib -lglut32
INCLUDEPATH += "$$PWD/my_include/cv"
LIBS +=  "$$PWD/my_lib/cv/libopencv_*.dll"
}
DISTFILES += \
    my_lib/glut32.lib \
    my_lib/libpng.lib \
    my_lib/glut32.dll \
    my_lib/libpng12.dll \
    my_lib/zlib1.dll \
    test_in/ImperxCamera0_18_10_123/image0.bmp \
    test_in/ImperxCamera1_18_10_123/image0.bmp \
    test_in/ImperxCamera2_18_10_123/image0.bmp \
    test_in/ImperxCamera3_18_10_123/image0.bmp \
    test_in/ImperxCamera0_18_10_123/test.txt \
    my_lib/cv/libopencv_calib3d331.dll \
    my_lib/cv/libopencv_core331.dll \
    my_lib/cv/libopencv_dnn331.dll \
    my_lib/cv/libopencv_features2d331.dll \
    my_lib/cv/libopencv_flann331.dll \
    my_lib/cv/libopencv_highgui331.dll \
    my_lib/cv/libopencv_imgcodecs331.dll \
    my_lib/cv/libopencv_imgproc331.dll \
    my_lib/cv/libopencv_ml331.dll \
    my_lib/cv/libopencv_objdetect331.dll \
    my_lib/cv/libopencv_photo331.dll \
    my_lib/cv/libopencv_shape331.dll \
    my_lib/cv/libopencv_stitching331.dll \
    my_lib/cv/libopencv_superres331.dll \
    my_lib/cv/libopencv_video331.dll \
    my_lib/cv/libopencv_videoio331.dll \
    my_lib/cv/libopencv_videostab331.dll \
    test_out/0.bmp \
    test_out/0_1.bmp \
    test_out/1.bmp \
    test_out/2.bmp \
    test_out/3.bmp \
    test_out/4.bmp \
    test_out/5.bmp \
    test_out/6.bmp \
    .gitignore

HEADERS += \
    GUI/GUI.h \
    my_include/gl.h \
    my_include/glext.h \
    my_include/glu.h \
    my_include/glut.h \
    my_include/png.h \
    my_include/pngconf.h \
    IO/IO.h \
    data/basic.h \
    image/image.h \
    my_include/cv/opencv/cv.h \
    my_include/cv/opencv/cv.hpp \
    my_include/cv/opencv/cvaux.h \
    my_include/cv/opencv/cvaux.hpp \
    my_include/cv/opencv/cvwimage.h \
    my_include/cv/opencv/cxcore.h \
    my_include/cv/opencv/cxcore.hpp \
    my_include/cv/opencv/cxeigen.hpp \
    my_include/cv/opencv/cxmisc.h \
    my_include/cv/opencv/highgui.h \
    my_include/cv/opencv/ml.h \
    my_include/cv/opencv2/calib3d/calib3d.hpp \
    my_include/cv/opencv2/calib3d/calib3d_c.h \
    my_include/cv/opencv2/core/cuda/detail/color_detail.hpp \
    my_include/cv/opencv2/core/cuda/detail/reduce.hpp \
    my_include/cv/opencv2/core/cuda/detail/reduce_key_val.hpp \
    my_include/cv/opencv2/core/cuda/detail/transform_detail.hpp \
    my_include/cv/opencv2/core/cuda/detail/type_traits_detail.hpp \
    my_include/cv/opencv2/core/cuda/detail/vec_distance_detail.hpp \
    my_include/cv/opencv2/core/cuda/block.hpp \
    my_include/cv/opencv2/core/cuda/border_interpolate.hpp \
    my_include/cv/opencv2/core/cuda/color.hpp \
    my_include/cv/opencv2/core/cuda/common.hpp \
    my_include/cv/opencv2/core/cuda/datamov_utils.hpp \
    my_include/cv/opencv2/core/cuda/dynamic_smem.hpp \
    my_include/cv/opencv2/core/cuda/emulation.hpp \
    my_include/cv/opencv2/core/cuda/filters.hpp \
    my_include/cv/opencv2/core/cuda/funcattrib.hpp \
    my_include/cv/opencv2/core/cuda/functional.hpp \
    my_include/cv/opencv2/core/cuda/limits.hpp \
    my_include/cv/opencv2/core/cuda/reduce.hpp \
    my_include/cv/opencv2/core/cuda/saturate_cast.hpp \
    my_include/cv/opencv2/core/cuda/scan.hpp \
    my_include/cv/opencv2/core/cuda/simd_functions.hpp \
    my_include/cv/opencv2/core/cuda/transform.hpp \
    my_include/cv/opencv2/core/cuda/type_traits.hpp \
    my_include/cv/opencv2/core/cuda/utility.hpp \
    my_include/cv/opencv2/core/cuda/vec_distance.hpp \
    my_include/cv/opencv2/core/cuda/vec_math.hpp \
    my_include/cv/opencv2/core/cuda/vec_traits.hpp \
    my_include/cv/opencv2/core/cuda/warp.hpp \
    my_include/cv/opencv2/core/cuda/warp_reduce.hpp \
    my_include/cv/opencv2/core/cuda/warp_shuffle.hpp \
    my_include/cv/opencv2/core/hal/hal.hpp \
    my_include/cv/opencv2/core/hal/interface.h \
    my_include/cv/opencv2/core/hal/intrin.hpp \
    my_include/cv/opencv2/core/hal/intrin_cpp.hpp \
    my_include/cv/opencv2/core/hal/intrin_neon.hpp \
    my_include/cv/opencv2/core/hal/intrin_sse.hpp \
    my_include/cv/opencv2/core/hal/intrin_vsx.hpp \
    my_include/cv/opencv2/core/utils/logger.hpp \
    my_include/cv/opencv2/core/utils/trace.hpp \
    my_include/cv/opencv2/core/affine.hpp \
    my_include/cv/opencv2/core/base.hpp \
    my_include/cv/opencv2/core/bufferpool.hpp \
    my_include/cv/opencv2/core/core.hpp \
    my_include/cv/opencv2/core/core_c.h \
    my_include/cv/opencv2/core/cuda.hpp \
    my_include/cv/opencv2/core/cuda.inl.hpp \
    my_include/cv/opencv2/core/cuda_stream_accessor.hpp \
    my_include/cv/opencv2/core/cuda_types.hpp \
    my_include/cv/opencv2/core/cv_cpu_dispatch.h \
    my_include/cv/opencv2/core/cv_cpu_helper.h \
    my_include/cv/opencv2/core/cvdef.h \
    my_include/cv/opencv2/core/cvstd.hpp \
    my_include/cv/opencv2/core/cvstd.inl.hpp \
    my_include/cv/opencv2/core/directx.hpp \
    my_include/cv/opencv2/core/eigen.hpp \
    my_include/cv/opencv2/core/fast_math.hpp \
    my_include/cv/opencv2/core/ippasync.hpp \
    my_include/cv/opencv2/core/mat.hpp \
    my_include/cv/opencv2/core/mat.inl.hpp \
    my_include/cv/opencv2/core/matx.hpp \
    my_include/cv/opencv2/core/neon_utils.hpp \
    my_include/cv/opencv2/core/ocl.hpp \
    my_include/cv/opencv2/core/ocl_genbase.hpp \
    my_include/cv/opencv2/core/opengl.hpp \
    my_include/cv/opencv2/core/operations.hpp \
    my_include/cv/opencv2/core/optim.hpp \
    my_include/cv/opencv2/core/ovx.hpp \
    my_include/cv/opencv2/core/persistence.hpp \
    my_include/cv/opencv2/core/ptr.inl.hpp \
    my_include/cv/opencv2/core/saturate.hpp \
    my_include/cv/opencv2/core/softfloat.hpp \
    my_include/cv/opencv2/core/sse_utils.hpp \
    my_include/cv/opencv2/core/traits.hpp \
    my_include/cv/opencv2/core/types.hpp \
    my_include/cv/opencv2/core/types_c.h \
    my_include/cv/opencv2/core/utility.hpp \
    my_include/cv/opencv2/core/va_intel.hpp \
    my_include/cv/opencv2/core/version.hpp \
    my_include/cv/opencv2/core/vsx_utils.hpp \
    my_include/cv/opencv2/core/wimage.hpp \
    my_include/cv/opencv2/dnn/all_layers.hpp \
    my_include/cv/opencv2/dnn/dict.hpp \
    my_include/cv/opencv2/dnn/dnn.hpp \
    my_include/cv/opencv2/dnn/dnn.inl.hpp \
    my_include/cv/opencv2/dnn/layer.details.hpp \
    my_include/cv/opencv2/dnn/layer.hpp \
    my_include/cv/opencv2/dnn/shape_utils.hpp \
    my_include/cv/opencv2/features2d/features2d.hpp \
    my_include/cv/opencv2/flann/all_indices.h \
    my_include/cv/opencv2/flann/allocator.h \
    my_include/cv/opencv2/flann/any.h \
    my_include/cv/opencv2/flann/autotuned_index.h \
    my_include/cv/opencv2/flann/composite_index.h \
    my_include/cv/opencv2/flann/config.h \
    my_include/cv/opencv2/flann/defines.h \
    my_include/cv/opencv2/flann/dist.h \
    my_include/cv/opencv2/flann/dummy.h \
    my_include/cv/opencv2/flann/dynamic_bitset.h \
    my_include/cv/opencv2/flann/flann.hpp \
    my_include/cv/opencv2/flann/flann_base.hpp \
    my_include/cv/opencv2/flann/general.h \
    my_include/cv/opencv2/flann/ground_truth.h \
    my_include/cv/opencv2/flann/hdf5.h \
    my_include/cv/opencv2/flann/heap.h \
    my_include/cv/opencv2/flann/hierarchical_clustering_index.h \
    my_include/cv/opencv2/flann/index_testing.h \
    my_include/cv/opencv2/flann/kdtree_index.h \
    my_include/cv/opencv2/flann/kdtree_single_index.h \
    my_include/cv/opencv2/flann/kmeans_index.h \
    my_include/cv/opencv2/flann/linear_index.h \
    my_include/cv/opencv2/flann/logger.h \
    my_include/cv/opencv2/flann/lsh_index.h \
    my_include/cv/opencv2/flann/lsh_table.h \
    my_include/cv/opencv2/flann/matrix.h \
    my_include/cv/opencv2/flann/miniflann.hpp \
    my_include/cv/opencv2/flann/nn_index.h \
    my_include/cv/opencv2/flann/object_factory.h \
    my_include/cv/opencv2/flann/params.h \
    my_include/cv/opencv2/flann/random.h \
    my_include/cv/opencv2/flann/result_set.h \
    my_include/cv/opencv2/flann/sampling.h \
    my_include/cv/opencv2/flann/saving.h \
    my_include/cv/opencv2/flann/simplex_downhill.h \
    my_include/cv/opencv2/flann/timer.h \
    my_include/cv/opencv2/highgui/highgui.hpp \
    my_include/cv/opencv2/highgui/highgui_c.h \
    my_include/cv/opencv2/imgcodecs/imgcodecs.hpp \
    my_include/cv/opencv2/imgcodecs/imgcodecs_c.h \
    my_include/cv/opencv2/imgcodecs/ios.h \
    my_include/cv/opencv2/imgproc/detail/distortion_model.hpp \
    my_include/cv/opencv2/imgproc/hal/hal.hpp \
    my_include/cv/opencv2/imgproc/hal/interface.h \
    my_include/cv/opencv2/imgproc/imgproc.hpp \
    my_include/cv/opencv2/imgproc/imgproc_c.h \
    my_include/cv/opencv2/imgproc/types_c.h \
    my_include/cv/opencv2/ml/ml.hpp \
    my_include/cv/opencv2/objdetect/detection_based_tracker.hpp \
    my_include/cv/opencv2/objdetect/objdetect.hpp \
    my_include/cv/opencv2/objdetect/objdetect_c.h \
    my_include/cv/opencv2/photo/cuda.hpp \
    my_include/cv/opencv2/photo/photo.hpp \
    my_include/cv/opencv2/photo/photo_c.h \
    my_include/cv/opencv2/shape/emdL1.hpp \
    my_include/cv/opencv2/shape/hist_cost.hpp \
    my_include/cv/opencv2/shape/shape.hpp \
    my_include/cv/opencv2/shape/shape_distance.hpp \
    my_include/cv/opencv2/shape/shape_transformer.hpp \
    my_include/cv/opencv2/stitching/detail/autocalib.hpp \
    my_include/cv/opencv2/stitching/detail/blenders.hpp \
    my_include/cv/opencv2/stitching/detail/camera.hpp \
    my_include/cv/opencv2/stitching/detail/exposure_compensate.hpp \
    my_include/cv/opencv2/stitching/detail/matchers.hpp \
    my_include/cv/opencv2/stitching/detail/motion_estimators.hpp \
    my_include/cv/opencv2/stitching/detail/seam_finders.hpp \
    my_include/cv/opencv2/stitching/detail/timelapsers.hpp \
    my_include/cv/opencv2/stitching/detail/util.hpp \
    my_include/cv/opencv2/stitching/detail/util_inl.hpp \
    my_include/cv/opencv2/stitching/detail/warpers.hpp \
    my_include/cv/opencv2/stitching/detail/warpers_inl.hpp \
    my_include/cv/opencv2/stitching/warpers.hpp \
    my_include/cv/opencv2/superres/optical_flow.hpp \
    my_include/cv/opencv2/video/background_segm.hpp \
    my_include/cv/opencv2/video/tracking.hpp \
    my_include/cv/opencv2/video/tracking_c.h \
    my_include/cv/opencv2/video/video.hpp \
    my_include/cv/opencv2/videoio/cap_ios.h \
    my_include/cv/opencv2/videoio/videoio.hpp \
    my_include/cv/opencv2/videoio/videoio_c.h \
    my_include/cv/opencv2/videostab/deblurring.hpp \
    my_include/cv/opencv2/videostab/fast_marching.hpp \
    my_include/cv/opencv2/videostab/fast_marching_inl.hpp \
    my_include/cv/opencv2/videostab/frame_source.hpp \
    my_include/cv/opencv2/videostab/global_motion.hpp \
    my_include/cv/opencv2/videostab/inpainting.hpp \
    my_include/cv/opencv2/videostab/log.hpp \
    my_include/cv/opencv2/videostab/motion_core.hpp \
    my_include/cv/opencv2/videostab/motion_stabilizing.hpp \
    my_include/cv/opencv2/videostab/optical_flow.hpp \
    my_include/cv/opencv2/videostab/outlier_rejection.hpp \
    my_include/cv/opencv2/videostab/ring_buffer.hpp \
    my_include/cv/opencv2/videostab/stabilizer.hpp \
    my_include/cv/opencv2/videostab/wobble_suppression.hpp \
    my_include/cv/opencv2/calib3d.hpp \
    my_include/cv/opencv2/core.hpp \
    my_include/cv/opencv2/cvconfig.h \
    my_include/cv/opencv2/dnn.hpp \
    my_include/cv/opencv2/features2d.hpp \
    my_include/cv/opencv2/flann.hpp \
    my_include/cv/opencv2/highgui.hpp \
    my_include/cv/opencv2/imgcodecs.hpp \
    my_include/cv/opencv2/imgproc.hpp \
    my_include/cv/opencv2/ml.hpp \
    my_include/cv/opencv2/objdetect.hpp \
    my_include/cv/opencv2/opencv.hpp \
    my_include/cv/opencv2/opencv_modules.hpp \
    my_include/cv/opencv2/photo.hpp \
    my_include/cv/opencv2/shape.hpp \
    my_include/cv/opencv2/stitching.hpp \
    my_include/cv/opencv2/superres.hpp \
    my_include/cv/opencv2/video.hpp \
    my_include/cv/opencv2/videoio.hpp \
    my_include/cv/opencv2/videostab.hpp \
    PMC/BinaryTreshold.h \
    PMC/DomainDetection.h \
    PMC/ParticleMaskCorrelation.h \
    PMC/PlanarContainer.h \
    MarkerIdentification/CalibrationTarget.h \
    MarkerIdentification/Marker.h \
    MarkerIdentification/MarkerSearcher.h \
    MarkerIdentification/MarkerSearcher_old.h \
    MarkerIdentification/MisalignmentCorr.h \
    MarkerIdentification/preciseTargPointsLoader.h
